apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-admin-sa
  annotations:
    kapp.k14s.io/change-group: "rbac"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-admin-role
  annotations:
    kapp.k14s.io/change-group: "rbac"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-admin-binding
  annotations:
    kapp.k14s.io/change-group: "rbac"
subjects:
- kind: ServiceAccount
  name: ns-admin-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-admin-role